const workExperience = {
	'ManyPets': {
		name: 'ManyPets',
		role: 'Frontend Developer',
		date: 'August 2022 - Present',
		desc: [
			'Working on a vet portal application that was handed over by external consultants',
			'Introducing reusable components throughout the codebase, making them accessible and adhering to perfect Lighthouse scores',
			'Utilising and building upon an in-house component library using Storybook',
			'Maintaining admin and client views while introducing feature flagging',
			'Introducing unit, component and system tests to an application that had 0% coverage',
			'Liaising with users of the application and collecting feedback to improve and provide a user-friendly application',
			'Introducing linting and other tools to maintain code efficiency and making sure that the codebase is using latest, up to standard coding practices',
		],
	},
	'Decision Tech': {
		name: 'Decision Technologies',
		role: 'Developer',
		date: 'June 2021 - August 2022',
		desc: [
			'Working on B2B and B2C applications using Typescript, Vue.js and Vuex for state management',
			'Migrating a B2C SPA (MoneySavingExpert) into a white-label platform while maintaining consistency and accessibility',
			'Creating features that have been A/B tested using Optimizely with the hope to produce better metrics and improve conversion throughout the website',
			'Using Storybook to create an internal library for importing and using UI components in many front-end platforms',
			'Writing unit tests using Jest to thoroughly test components and stores to ensure that every possible use case have been met and minimise errors',
			'Reviewing pull requests while also making suggestions and finding room for improvement where appropriate',
			'Working in a diverse team of frontend and backend engineers following a strict Kanban approach',
			'Using Postman to test and understand endpoints that the backend team have worked on to use them in frontend tickets',
		],
	},
	Garrison: {
		name: 'Garrison Technology Limited',
		role: 'Software Engineer',
		date: 'July 2020 - June 2021',
		desc: [
			'Working in an Agile environment formed of hardware, firmware, DevOps, customer success engineers, marketing specialists and sales representatives',
			'Creating and implementing mock APIs for development environments using FeathersJS',
			'Contributing to UX/UI decisions and creating designs with an emphasis on accessibility for customer facing applications',
			'Using Storybook to create an internal library for importing and using UI components in many front-end platforms',
			'Creating pipelines using GitLab CI to ensure that all repositories are monitored and tested when new code changes take place before deployment',
			'Writing and reviewing end-to-end tests using Cypress and Puppeteer to enforce rigorous testing on newly added features and components',
			'Liaising with customer success engineers to identify and improve user interfaces',
			'Working on projects that have tight deadlines whilst also ensuring that all work was to a high standard',
		],
	},
	KITC: {
		name: 'Kent IT Consultancy',
		role: 'IT Consultant',
		date: 'September 2019 - May 2020',
		desc: [
			'Working in teams of at least four consultants to help SMEs in Kent to work on a multitude of projects.',
			'Communicating with key stakeholders to define the scope and directions of projects',
			'Consulting on solutions for clients and providing a digital roadmap for their solutions',
			'Working on full lifecycle projects, helping clients understand how to work more digitally',
			'Having commercial awareness to explore and investigate possible solutions that meet client requirements',
			'Learning IBM’s Design Thinking Process in order to solve business issues with a technical solution',
		],
	},
	'Code First Girls': {
		name: 'Code First Girls',
		role: 'Web Development Instructor',
		date: 'October 2019 - December 2019',
		desc: [
			'Teaching introduction to web development after university hours to students from different courses',
			'Presenting topics such as HTML, CSS, JavsScript, Bootstrap, GitHub, VSCode & hosting websites',
			'Holding a competition for best website made by groups and monitoring two groups for support',
		],
	},
	'Holiday Extras': {
		name: 'Holiday Extras Limited',
		role: 'Front-End Engineer',
		date: 'July 2018 - August 2019',
		desc: [
			'Working in an Agile environment in teams formed of engineers, content writers, testers and agile coaches',
			'Using JavaScript and third-party frameworks/libraries such as React, Moment, Redux, Lodash, Lottie etc.',
			'Leading meetings such as sprint planning, retrospectives as well as demos to stakeholders while communicating clearly and effectively to teams and board members',
			'Taking lead on projects that had strict deadlines, ensuring all work met deadlines and were to a high standard',
			'Mentoring new engineers, making sure that they integrated well into the company',
		],
	},
	'Uni of Kent': {
		name: 'School of Computing',
		role: 'Peer Tutor & Ambassador',
		date: 'September 2017 - May 2020',
		desc: [
			'Mentoring first and second year computer science students with assignments',
			'Monitoring first year Object Oriented Programming classes and assisting with problems and answering related questions',
			'Assisting during university open days to showcase the School of Computing',
			'Used presentation and communication skills to emphasise the key features and benefite that the School of Computing offers',
			'Giving talks to placement students about what a Year in Industry is like and what it offers',
		],
	},
};

export default workExperience;
