const workExperience = {
  Hometrack: {
    name: "Hometrack (part of Houseful)",
    role: "Full Stack Engineer",
    date: "June 2024 - Present",
    desc: []
  },
  Checkatrade: {
    name: "Checkatrade",
    role: "Senior Frontend Engineer",
    date: "May 2023 - April 2024",
    desc: [
      "Worked alongside product managers, designers, and other engineers to transform creative concepts into refined digital experiences at an agile (2-week) cadence",
      "Played a pivotal role within the core frontend team to optimise Checkatrade.com using Next.js and TypeScript, prioritising AB testing methodologies to continually enhance user experience and performance",
      "Actively participated in 'code rampages' to reduce technical debt and enhance the codebase. This included transitioning areas from JavaScript to TypeScript, creating reusable and accessible components, while also focusing on testing and code coverage using Jest, React Testing Library, and Playwright",
      "Introduced Storybook to facilitate code reusability across teams and enhance observability by establishing a toolkit as the brand guideline. Developed high-standard components with a focus on semantics and accessibility",
      "Took the lead in migrating Strapi from v3 to v4 by creating new GCP projects using Terraform, managing database backups with PostgreSQL, and actively using the Strapi APIs to implement endpoints for complex business logic",
      "Led the transition from Sentry to Datadog in the frontend, providing comprehensive training to wider teams to effectively utilise Datadog. This included demonstrating how to search/filter logs, create dashboards, alerts, monitors and how to write queries, all while ensuring proactive error detection and resolution",
      "Collaborated with a team to develop a SPA utilising Google's Solar API, enabling homeowners to visualise solar panel installations and potential energy savings which in turn returns users to the Checkatrade website promoting specialists in solar panels",
      "Integrated pino.js and pino-http in the Node backend to format and categorise logs being sent to GCP, optimising logging processes for improved system performance and troubleshooting",
    ],
  },
  ManyPets: {
    name: "ManyPets",
    role: "Front-end Developer",
    date: "August 2022 - April 2023",
    desc: [
      "Worked on a vet portal application previously managed by external consultants",
      "Migrated the application from Vue 2 to Vue 3, transitioning from the Options API to the Composition API",
      "Implemented state management using Pinia and VueUse for persistent storage",
      "Designed reusable, accessible components and achieved optimal Lighthouse scores",
      "Expanded the in-house component library with Storybook",
      "Maintained and enhanced admin and client views while adding feature flagging",
      "Introduced comprehensive unit, component and system tests to an application that had 0% coverage",
      "Communicated with users to gather feedback and continually improve the application's UI",
      "Integrated linting and other tools to maintain code efficiency and best coding practices",
      "Maintained backend code built with Node.js and AWS Amplify",
      "Utilized Sentry for error tracking, alerting, and monitoring",
      "Monitored backend logs with Cloudwatch, addressing errors and failures during investigations",
      "Tracked and analysed user behaviour with Heap.io to identify areas for improvement and optimize the application’s performance",
    ],
  },
  Moneysupermarket: {
    name: "Moneysupermarket",
    role: "Developer",
    date: "June 2021 - August 2022",
    desc: [
      "Developed B2B and B2C applications with a focus on Typescript, Vue.js and Vuex",
      "Successfully transformed a B2C SPA (MoneySavingExpert) into a white-label platform while preserving consistency and accessibility",
      "Implemented features that underwent A/B testing using Optimizely to drive better metrics and improve conversion",
      "Conducted comprehensive testing of components and stores through Jest unit tests, reducing errors and covering all use cases",
      "Conducted code reviews, provided suggestions, and identified areas for improvement in pull requests",
      "Worked collaboratively in a team of front-end and backend engineers, adhering to Agile methodologies",
      "Utilized Postman to test and comprehend backend endpoints for implementation in front-end projects",
    ],
  },
  Garrison: {
    name: "Garrison Technology",
    role: "Software Engineer",
    date: "July 2020 - June 2021",
    desc: [
      "Developed multiple front-end applications using React and Redux, providing a seamless user experience",
      "Collaborated with the backend teams to ensure seamless communication between the front-end and Python API",
      "Played a key role in UX/UI decision making and designed customer-facing applications with accessibility in mind",
      "Utilized Storybook to establish an internal library for efficient use of UI components across multiple front-end platforms",
      "Implemented and reviewed comprehensive end-to-end testing using Cypress and Puppeteer to validate new features and components",
      "Established pipelines using GitLab CI to monitor and test all environments, ensuring the reliability of code changes",
      "Provided mentorship to new starters and placement students, imparting essential front-end web development skills and knowledge",
    ],
  },
  "Holiday Extras": {
    name: "Holiday Extras Limited",
    role: "Front-end Engineer",
    date: "July 2018 - August 2019",
    desc: [
      "Experienced in working within an Agile environment, collaborating with cross-functional teams including engineers, content writers, testers, and agile coaches",
      "Developed new features on the Holiday Extras website by utilizing JavaScript and implementing libraries such as ReactJS, NodeJS, Backbone, Moment, and Lottie",
      "Demonstrated strong code review skills and ensured comprehensive unit tests were written for all delivered work",
      "Employed GitHub as the version control system, submitting and reviewing code daily",
      "Played a key role in UX/UI decision making and executed redesigns of multiple sections of the website",
      "Guaranteed cross-browser compatibility, ensuring that all features were supported on Chrome, Safari, Firefox, and Internet Explorer",
    ],
  },
};

export default workExperience;
